"""Stable, implementation-independent EJAgent Core contracts."""

from ejagent.contracts.audit import AuditReader, RunAudit
from ejagent.contracts.context import (
    ContextBuildError,
    ContextCompactionOutput,
    ContextCompactionRequest,
    ContextCompactor,
    ContextCompactorError,
    ContextPipeline,
    ContextProtocolError,
    ContextRequest,
    ContextView,
)
from ejagent.contracts.control import (
    CancellationSource,
    CancellationToken,
    RunCancelledError,
)
from ejagent.contracts.conversation import ConversationSnapshot
from ejagent.contracts.json import (
    JsonObject,
    JsonScalar,
    JsonValue,
    MutableJsonValue,
    freeze_json_object,
    freeze_json_value,
    thaw_json_value,
)
from ejagent.contracts.lifecycle import ManagedResource
from ejagent.contracts.messages import (
    AssistantMessage,
    ContextMessage,
    ContextSummary,
    ConversationMessage,
    SystemMessage,
    ToolCall,
    ToolResultMessage,
    TransientInstruction,
    UserMessage,
    is_context_message,
    is_conversation_message,
)
from ejagent.contracts.model import (
    ModelCallError,
    ModelPort,
    ModelProtocolError,
    ModelRequest,
    ModelResponseCompleted,
    ModelStreamEvent,
    ModelTextDelta,
    ModelThinkingDelta,
    ModelUsage,
)
from ejagent.contracts.runs import (
    AuditRecord,
    FailureCode,
    RunDelta,
    RunFailure,
    RunIntent,
    RunLimits,
    RunOutcome,
    RunPhase,
    RunResult,
    RunSpec,
    RunStatus,
    StopReason,
)
from ejagent.contracts.session import (
    SessionCommit,
    SessionConflictError,
    SessionSnapshot,
    SessionStore,
    SessionStoreError,
)
from ejagent.contracts.tools import (
    ToolControl,
    ToolDefinition,
    ToolEffect,
    ToolExecutionError,
    ToolExecutionResult,
    ToolExecutor,
    ToolProtocolError,
    ToolSemantics,
)
from ejagent.contracts.usage import RunUsage

__all__ = [
    "AssistantMessage",
    "AuditReader",
    "AuditRecord",
    "CancellationSource",
    "CancellationToken",
    "ContextMessage",
    "ContextBuildError",
    "ContextCompactionOutput",
    "ContextCompactionRequest",
    "ContextCompactor",
    "ContextCompactorError",
    "ContextPipeline",
    "ContextProtocolError",
    "ContextRequest",
    "ContextSummary",
    "ContextView",
    "ConversationMessage",
    "ConversationSnapshot",
    "FailureCode",
    "JsonObject",
    "JsonScalar",
    "JsonValue",
    "ManagedResource",
    "MutableJsonValue",
    "ModelCallError",
    "ModelPort",
    "ModelProtocolError",
    "ModelRequest",
    "ModelResponseCompleted",
    "ModelStreamEvent",
    "ModelTextDelta",
    "ModelThinkingDelta",
    "ModelUsage",
    "RunDelta",
    "RunAudit",
    "RunFailure",
    "RunIntent",
    "RunLimits",
    "RunOutcome",
    "RunPhase",
    "RunResult",
    "RunSpec",
    "RunStatus",
    "RunUsage",
    "RunCancelledError",
    "SessionCommit",
    "SessionConflictError",
    "SessionSnapshot",
    "SessionStore",
    "SessionStoreError",
    "StopReason",
    "SystemMessage",
    "ToolCall",
    "ToolControl",
    "ToolDefinition",
    "ToolEffect",
    "ToolExecutionError",
    "ToolExecutionResult",
    "ToolExecutor",
    "ToolProtocolError",
    "ToolResultMessage",
    "ToolSemantics",
    "TransientInstruction",
    "UserMessage",
    "freeze_json_object",
    "freeze_json_value",
    "is_context_message",
    "is_conversation_message",
    "thaw_json_value",
]
